fm_elfinder:
    instances:
        default:
            locale: fr
            editor: ckeditor
            relative_path: false
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','image/webp']
                        upload_deny: ['all']
                        upload_max_size: 2M
