vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%user_images%'
            upload_destination: '%kernel.project_dir%/public%user_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: false
        article_images:
            uri_prefix: '%article_images%'
            upload_destination: '%kernel.project_dir%/public%article_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        session_images:
            uri_prefix: '%session_images%'
            upload_destination: '%kernel.project_dir%/public%session_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        challenge_images:
            uri_prefix: '%challenge_images%'
            upload_destination: '%kernel.project_dir%/public%challenge_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
